version: '3'
services:
  master:
    build: jenkins-server/jenkins-master
    ports:
      - "50000:50000"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
  nginx:
    build: jenkins-server/jenkins-nginx
    ports:
      - "80:80"
    networks:
      - jenkins-net
  slave-bch:
    build: slaves/jenkins-slave-ubuntu
  proxy:
    build: ./docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      jenkins-net:
        aliases:
          - proxy1
volumes:
  jenkins-data:
  jenkins-log:
networks:
  jenkins-net:


