version: '3'
services:
  master:
    build: jenkins-server/jenkins-master
    ports:
      - "50000:50000"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
  nginx:
    build: jenkins-server/jenkins-nginx
    ports:
      - "80:80"
    networks:
      - jenkins-net
  slave-ubuntu:
    build: slaves/jenkins-slave-ubuntu
    extra_hosts:
      - lablnx392:200.14.140.170
      - LABLNX392:200.14.140.170
      - loginmulticanalbch:152.139.147.83
      - tasacionesweb:152.139.146.127
      - tasacioneswls:152.139.146.127
      - login.qa.labchile.cl:200.14.140.170
      - portalpersonas.qa.labchile.cl:200.14.132.93
      - portalempresas.qa.labchile.cl:200.14.132.96
  proxy:
    build: ./docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      jenkins-net:
        aliases:
          - proxy1
volumes:
  jenkins-data:
  jenkins-log:
networks:
  jenkins-net:


