version: '3'

services:
  kuzzle:
    image: kuzzleio/kuzzle
    restart: always
    ports:
      - "7512:7512"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - redis
      - elasticsearch
    environment:
      - kuzzle_services__storageEngine__client__node=http://elasticsearch:9200
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_server__protocols__mqtt__enabled=true
      - NODE_ENV=production
    healthcheck:
      test: "curl http://kuzzle:7512/_healthCheck"
      interval: "60s"
      timeout: "5s"
      retries: 3

  redis:
    image: redis:5
    restart: always

  elasticsearch:
    build: ./elasticsearch
    restart: always
    ports:
      - "9200:9200"
    ulimits:
      nofile: 65536
    volumes:
      - data-prod:/usr/share/elasticsearch/data
      - backup-prod:/opt/elasticsearch/backup

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    ports:
      - 5601:5601
volumes:
  data-prod:
  backup-prod:

